name: theweeklymuscle
favicon: null
layout_spectrum: 0.25341
typography_spectrum: 0.13705
title: The Weekly Muscle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#051107'
    - '#dedede'
    - '#576959'
    - '#3d3626'
    - '#abafac'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
